const char js_str[] = ""
  "function monitor() {"
  "const request = new Request('http://192.168.3.1/voltage');"
  "fetch(request)"
  ".then(response => response.json())"
  ".then(data => {"
  "let valueDisplay = document.getElementById('value');"
  "valueDisplay.innerHTML = data['voltage'];"
  "})"
  ".catch(error => {console.error(error);});"
  "}"
  "setInterval(monitor, 1000);"
  "function turn_feedback(state) {"
  "const request = new Request('http://192.168.3.1/feedback/'+state);"
  "fetch(request);"
  "}"
  "function change_power(ratio) {"
  "const request = new Request('http://192.168.3.1/power/'+ratio);"
  "fetch(request);"
  "}"
  "function set_target() {"
  "const request = new Request('http://192.168.3.1/set_target');"
  "fetch(request);"
  "}"
  "";
